### ISSUE TITLE
Readme link redirects back to GitHub

### ISSUE THREAD

**Issue by Kolt45** [stevedem/splitpdfs#3]
The link in the readme redirects to GitHub. I am curious what the steps of your Logic App look like but cannot view. Can you help? Thanks!

**Comment by stevedem** [comment]
Hi @Kolt45 - thanks for posting this. I'm in the process of re-hosting my personal blog and will update this as soon as I am able.

**Comment by stevedem** [comment]
I've re-hosted my blog using GitHub pages and this blog post is now pointing to correct URL:

https://stevedem.github.io/Splitting-PDFs/
